version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20.x
  pre_build:
   commands:
       - echo "creating folder"
       - echo "userName [${userName}]"
       - echo "userPassword [${userPassword}]"
       - echo "bucketPrefix [${bucketPrefix}]"
       - mkdir -p ./build
  build:
    commands:
        - echo "hello world"
        - echo "hello $(date)" > build/out.txt
        - sed 's/hello world/DEPLOY/' buildspec.yml > build/buildspec.yml
artifacts:
   files:
     - '**/*'
   base-directory: './build'
   discard-paths: yes
