version: 0.2

phases:
  install:
   runtime-versions:
      nodejs: 20.x
   commands:
       - npm install -g aws-cdk@2.117.0
       - npm -g install typescript@5.3.3
  pre_build:
   commands:
       - echo "creating folder"
       - echo "userName [${userName}]"
       - echo "userPassword [${userPassword}]"
       - echo "bucketPrefix [${bucketPrefix}]"
       - cdk --version
       - tsc --version
       - mkdir -p ./build
  build:
    commands:
        - aws sts get-caller-identity
        - echo "hello world"
        - echo "hello $(date)" > build/out.txt
        - npm install
        - npm run build
        - cdk bootstrap -y
        - cdk ls
        - cdk deploy -y
artifacts:
   files:
     - '**/*'
   base-directory: './build'
   discard-paths: yes
