version: 0.2

phases:
  pre_build:
   commands:
       - echo "creating folder"
       - mkdir -p ./build
  build:
    commands:
        - echo "hello world"
        - echo "hello $(date)" > build/out.txt
        - sed 's/hello world/DEPLOY/' buildspec.yml > build/buildspec.yml
artifacts:
   files:
      - ./build/*
